### ISSUE TITLE
Keyboard.GetState() dies a horrible death through access violation

### ISSUE THREAD

**Issue by nattthebear** [andykorth/opentk#13]
In KeyboardState.cs, internal void MergeBits():

Codes has type int[256].  This iteration is just plain wrong:

``` C#
int* c2 = other.Codes;
fixed (int* c1 = Codes)
{
    for (int i = 0; i < short.MaxValue; i++)
        *(c1 + i) |= *(c2 + i);
}
```

**Comment by andykorth** [comment]
Yep, that looks pretty crazy to me.

**Comment by andykorth** [comment]
I've made a quick fix in f38e71760161a5ac9257f3e23f79d4100583de50. 

Paging @artfunkel, in case he has any comments on this. (does that send automatic notifications?)

**Comment by Artfunkel** [comment]
Yes it does! Definitely a mistake on my part, I meant to use byte.MaxValue. Your fix is much better though.

**Comment by andykorth** [comment]
Okay, I'll call this one wrapped up!
