### ISSUE TITLE
Nsis build configuration fails

### ISSUE THREAD

**Issue by LaylBongers** [andykorth/opentk#14]
The errors while building are:
"The command "makensis opentk.nsi exited with code 9009"
"The command "doxygen" exited with code 9009"
"The command "7z a -tzip opentk.zip opentk\" exited with code 9009"
From what I gather from stackoverflow, using macros like $(SolutionDir) to get the full path could fix the problem but I didn't test this out myself.

**Comment by andykorth** [comment]
What's Nsis?

**Comment by Sappharad** [comment]
http://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System
It's a popular installer package by the developers who made WinAmp. 

From the OpenTK documentation, it sounds like nsis, doxygen, and 7zip command line must be supplied by the developer doing the build for that configuration. (And they definitely aren't included in the repo).
http://www.opentk.com/doc/install

This sounds like an environment problem and not an issue with OpenTK. You must provide those things yourself where the compiler is expecting to find them.

**Comment by LaylBongers** [comment]
Ah, alright, I assume this is for compiling an installer as provided by the OpenTK website itself?
Perhaps it's a good idea to add that developers compiling this need this to a wiki page.
