### ISSUE TITLE
KeyboardState IsConnected always false

### ISSUE THREAD

**Issue by jhauberg** [andykorth/opentk#2]
`Keyboard.GetState().IsConnected` always return `false` on Windows 8.

**Comment by jhauberg** [comment]
Works on both Win8 and 7 when using the code suggested here [http://www.opentk.com/node/3198#comment-14023](http://www.opentk.com/node/3198#comment-14023).

**Comment by andykorth** [comment]
Thanks Jacob, I don't have access to Windows 8, but I can add that fix to this Github repository. Thanks for verifying that it works. Will look at it soon.

**Comment by andykorth** [comment]
Should be fixed now, Thanks! I don't have access to a windows dev machine, but I'd love to know if the fix works on Windows XP and Windows 8. 

Here's the diff:
https://github.com/andykorth/opentk/commit/fa422dca2aca1efc459f47db5ef3b8990c615821
